services:
  core-engine:
    build:
      context: ../core-engine
      dockerfile: ../infra/core.Dockerfile
    networks:
      - netsim_net

  ai-service:
    build:
      context: ../ai-service
      dockerfile: ../infra/ai.Dockerfile
    ports:
      - "8000:8000"
    networks:
      - netsim_net

  dashboard:
    build:
      context: ../dashboard
      dockerfile: ../infra/dashboard.Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - ai-service
    networks:
      - netsim_net

networks:
  netsim_net:
    driver: bridge